from numpy import save
from algorithms import *

if __name__ == "__main__":
    # ################################## PARTE 3 ######################################
    # g1 = barasiAlbertGraph(30, 4)
    # saveGraph(g1)
    # dg1 = g1.Dijkstra(7)
    # saveGraph(dg1, g1.typee)
    # g2 = barasiAlbertGraph(150, 4)
    # saveGraph(g2)
    # dg2 = g2.Dijkstra(7)
    # saveGraph(dg2, g2.typee)
    # g1 = dorogovtsevMendesGraph(30)
    # saveGraph(g1)
    # dg1 = g1.Dijkstra(11)
    # saveGraph(dg1, g1.typee)
    # g2 = dorogovtsevMendesGraph(150)
    # saveGraph(g2)
    # dg2 = g2.Dijkstra(11)
    # saveGraph(dg2, g2.typee)
    # g1 = erdosRenyiGraph(30, 300)
    # saveGraph(g1)
    # dg1 = g1.Dijkstra(9)
    # saveGraph(dg1, g1.typee)
    # g2 = erdosRenyiGraph(150, 6000)
    # saveGraph(g2)
    # dg2 = g2.Dijkstra(9)
    # saveGraph(dg2, g2.typee)
    # g1 = geographicGraph(30, r=0.4)
    # saveGraph(g1)
    # dg1 = g1.Dijkstra(9)
    # saveGraph(dg1, g1.typee)
    # g2 = geographicGraph(150, r=0.3)
    # saveGraph(g2)
    # dg2 = g2.Dijkstra(9)
    # saveGraph(dg2, g2.typee)
    # g1 = gilbertGraph(30, p=0.4)
    # saveGraph(g1)
    # dg1 = g1.Dijkstra(26)
    # saveGraph(dg1, g1.typee)
    # g2 = gilbertGraph(150, p=0.3)
    # saveGraph(g2)
    # dg2 = g2.Dijkstra(26)
    # saveGraph(dg2, g2.typee)
    g1 = gridGraph(6, 6)
    saveGraph(g1)
    dg1 = g1.Dijkstra(10)
    saveGraph(dg1, g1.typee)
    g2 = gridGraph(12, 12)
    saveGraph(g2)
    dg2 = g2.Dijkstra(10)
    saveGraph(dg2, g2.typee)
